name: tinker-lab-env
channels:
  - defaults
dependencies:
  - python=3.6.6
  - pip=19.1.1
  - pip:
    - appnope==0.1.0
    - attrs==19.1.0
    - backcall==0.1.0
    - certifi==2020.12.5
    - cryptography=3.4.6
    - cycler==0.10.0
    - python-dateutil==2.8.0
    - decorator==4.3.2
    - defusedxml==0.5.0
    - dill==0.3.1.1
    - entrypoints==0.2.3
    - et_xmlfile==1.0.1
    - ipykernel==5.1.0
    - IPython==7.3.0
    - ipython_genutils==0.2.0
    - ipywidgets==8.0.0a0
    - jdcal==1.4.1
    - Jinja2==2.10
    - joblib==0.15.1
    - jsonschema==2.6.0
    - jupyter-client==6.1.7
    - jupyter-core==4.6.3
    - kiwisolver==1.0.1
    - lxml==4.6.2
    - MarkupSafe==1.1.0
    - matplotlib==3.1.1
    - mistune==0.8.4
    - nbconvert==5.4.1
    - nbformat==4.4.0
    - notebook==5.7.8
    - numpy==1.16.4
    - openpyxl==2.6.3
    - pandas==1.0.3
    - pandocfilters==1.4.2
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - Pillow==8.1.2
    - prompt_toolkit==2.0.9
    - ptyprocess==0.5.2
    - Pygments==2.3.1
    - pyparsing==2.3.1
    - pyrsistent==0.14.11
    - pytz==2021.1
    - Send2Trash==1.5.0
    - setuptools==40.8.0
    - scikit-learn==0.23.1
    - scipy==1.4.0
    - simplegeneric==0.8.1
    - six==1.15.0
    - testpath==0.4.2
    - threadpoolctl==2.0.0
    - tornado==4.5.3
    - traitlets==4.3.2
    - version_information==1.0.3
    - wcwidth==0.1.7
    - widgetsnbextension==4.0.0a0
    - xlrd==1.2.0
    - pyzmq==17.1.2
