name: tinker-lab-env
channels:
  - defaults
dependencies:
  - python=3.6.6
  - pip=19.1.1
  - pip:
    - appnope==0.1.2
    - async_generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bokeh==2.3.1
    - certifi==2020.12.5
    - cffi==1.14.5
    - cryptography==3.4.6
    - cvxopt==1.2.6
    - cycler==0.10.0
    - python-dateutil==2.8.1
    - decorator==5.0.7
    - defusedxml==0.7.1
    - dill==0.3.3
    - entrypoints==0.3
    - et_xmlfile==1.0.1
    - importlib-metadata==4.0.1
    - ipykernel==5.5.3
    - IPython
    - ipython_genutils==0.2.0
    - ipywidgets==8.0.0a0
    - jdcal==1.4.1
    - Jinja2==2.11.3
    - joblib==0.15.1
    - jsonschema==3.2.0
    - jupyter-client==6.2.0
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - kiwisolver==1.0.1
    - lxml==4.6.2
    - MarkupSafe==1.1.1
    - matplotlib==3.1.1
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.3.0
    - numpy==1.16.4
    - openpyxl==2.6.3
    - packaging==20.9
    - pandas==1.0.3
    - pandocfilters==1.4.3
    - patsy==0.5.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - Pillow==8.1.2
    - prometheus-client==0.10.1
    - prompt_toolkit==3.0.18
    - ptyprocess==0.7.0
    - Pygments==2.8.1
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - pytz==2021.1
    - regex==2021.4.4
    - Send2Trash==1.5.0
    - setuptools==56.0.0
    - scikit-learn==0.23.1
    - scipy==1.4.0
    - simplegeneric==0.8.1
    - six==1.15.0
    - statsmodels==0.12.2
    - testpath==0.4.4
    - threadpoolctl==2.0.0
    - tornado==6.1.0
    - traitlets
    - typing_extensions==3.7.4.3
    - version_information==1.0.3
    - wcwidth==0.2.5
    - widgetsnbextension==4.0.0a0
    - xlrd==1.2.0
    - zipp==3.4.1
    - PyYAML==5.4.1
    - pyzmq==17.1.2
